Refactor reChart to handle new chartSeries
plot_object$subset doesn't work for plot.xts based object. The issue occurs
in xts:::chart.lines where it calls "lines" to create original series for x
by plot_object$Env$xycoords$x and the subset series for y. So it returns an
error: "'x' and 'y' lengths differ." See issue #146.